# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_choices', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='M', max_length=5)),
                ('room_type', models.CharField(choices=[('Shared', 'Shared'), ('Private', 'Private'), ('Married', 'Married')], default='Private', max_length=7)),
                ('contract_length', models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Fall/Winter', 'Fall/Winter'), ('Winter/Summer', 'Winter/Summer'), ('Summer/Fall', 'Summer/Fall'), ('Full Year', 'Full Year'), ('Other', 'Other')], default='Fall/Winter', max_length=15)),
                ('building_type', models.CharField(choices=[('Apt', 'Apartment'), ('House', 'House')], default='Apt', max_length=10)),
                ('BYU_housing', models.BooleanField(default=True)),
            ],
        ),
    ]
