# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexname',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complexname',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
