# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apt_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apt/Suite #'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenity',
            field=models.ManyToManyField(blank=True, null=True, to='main.Amenities'),
        ),
    ]
