# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='amenity',
        ),
        migrations.AddField(
            model_name='listing',
            name='amenity',
            field=models.ManyToManyField(to='main.Amenities'),
        ),
    ]
