# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_choices', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='M', max_length=5)),
                ('room_type', models.CharField(choices=[('Shared', 'Shared'), ('Private', 'Private'), ('Married', 'Married')], default='Private', max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
