# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160218_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='BYU_housing',
            field=models.BooleanField(default=False),
        ),
    ]
