# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160219_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apartment_complex',
            field=models.BooleanField(default=True),
        ),
    ]
