# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160225_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexname',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complexname',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
