# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160216_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='building_type',
            field=models.CharField(choices=[('Apt', 'Apartment'), ('House', 'House')], default='Apt', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='contract_length',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Fall/Winter', 'Fall/Winter'), ('Winter/Summer', 'Winter/Summer'), ('Summer/Fall', 'Summer/Fall'), ('Full Year', 'Full Year'), ('Other', 'Other')], default='Fall/Winter', max_length=15),
        ),
    ]
