# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_apartment_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='upload_image',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
