# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160219_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='complex_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ComplexName'),
            preserve_default=False,
        ),
    ]
