# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='roommates',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
