# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_listing_roommates'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
