# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160219_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
