# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complexname',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
