# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160219_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complexname',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Amenities'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='complex_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ComplexName'),
        ),
    ]
